src/gz immortalwrt_core https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/targets/msm89xx/msm8916/packages
src/gz immortalwrt_base https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/packages/aarch64_generic/base
src/gz immortalwrt_luci https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/packages/aarch64_generic/luci
src/gz immortalwrt_packages https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/packages/aarch64_generic/packages
src/gz immortalwrt_routing https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/packages/aarch64_generic/routing
src/gz immortalwrt_telephony https://mirrors.pku.edu.cn/immortalwrt/releases/snapshots/packages/aarch64_generic/telephony
